[project]
name = "devices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bokeh>=3.9.0",
    "gpiozero>=2.0.1",
    "matplotlib>=3.10.3",
    "numpy>=2.3.0",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.0",
    "pillow>=11.2.1",
    "seaborn>=0.13.2",
    "smbus2>=0.5.0",
]

[dependency-groups]
dev = ["pandas-stubs~=2.3.0"]
